keys:
  - key:
      ssid: 2
      privateKey: >
                    -----BEGIN RSA PRIVATE KEY-----
                    MIIEowIBAAKCAQEAhfW0BC9dQGUX1MSR+1JZbUSmsiMhRjlbhHayFXWzHGoCXdfS
                    DI+zqp10fltGhDnceRDkVy3Ex0SL/FJQUSQJbyCXxCy0IMZvbKoxmaODXBgMg6/y
                    NwE7sO/a39U+hJwqm/AJ+A15QmozsK1DmIe+cHWUUyeebPN0+qXp20cB7mVphCNH
                    z4DbjpzA5cpc/WQiRqndeYGRjTMifOmNV68TvyYnM3yPluTBDHrGo8FkX91vJ5Ru
                    eiT6HqXtt+a+pc/Xp2QIVQlgc+i0wvzxFHGhE6wuSVWKckmoJVdakwcqx2BehRX9
                    HakMubdSRT8pEb3BJ5/dkby0OAuS0XBBDD5c5wIDAQABAoIBAFhIqH3FlUhWF5GS
                    hr7B88uuXcmym0BDlsvCyfSYoBUOzEZ6cKT0o6zCnj6T+vIzi9iByGqn8DJ/O15s
                    BSCkhk8lhL+10nRzMoXD2HJvr6em9cBn2VJkzqj6Oh4f1Fbi8LXaSUef4ZVilnRO
                    i+jfNSO6aakvyBn3jNWPOILZ1iz80oGj+9Ji9GROPas+OBywfuGwb02TjGM9bYGN
                    j8HU0w8Uq8BrOiCSphLpbVST/ccBE8K2Y0co4JmWKHIc1XtHqITz3A0yblBJJAQW
                    /SH76AEc3jETXvbDxXUGWBTGRXXVnNpLD3TZczNpXvCVfppBpz7WzBbjrNLps/fy
                    6U2YFQECgYEA3qZXx152LDnNch7/wMAfSucEjnA+ZGNuge47jEgZNBXJmYNVr67R
                    rJ3DbgyQApFDVIp4UMRgPFQiHuIy8xbNkfQHqnwtxUr1XrD3BMmlmIWcdQh0urZT
                    ApHufLq8UV60H/Gm64PJirxJYYS+vOpblhPCWnRfqr4U9BisfpIaUIECgYEAmgZ7
                    YzHcChkpOQ/+F24TUon2uu2f++70NkD660g72kS2yiB3O1oaQnuzG1DJxe9BbFUt
                    SwOV1dKtkg5aO3Nt0NxeW6vnRIlDoraRKBjue23antMWBniDkdPl+HUHM4BHwFP0
                    WS8Vf3vMjz6X7zX085EbHpeHj2cu2IN8dFYbeWcCgYBedzk7D6sX7JZsWxasE1ez
                    kfzu6lSuhzl1yzxcsqJu5OeaSIzsc0Hm+TDX2mCnljZ5Ah82NXuXXSL084gmd4BU
                    8rLl9LX+xWUB/hdwYpXt9pKBXUsZhQ4HQx9qsFgCNio6e28U8d9rC6QeyhGbWdvt
                    +wg1FLcaXHfLcUSOlzKvAQKBgCE3JqK0nOQcmvQwS7ZXyZjyIaAcIHUfCdEtYC8f
                    C7E9QkICkFPfUWxm6rAIUwr5Vp17HOJhao2K+l1V9QV/Ff6Fl1+jiaMRCuHrBxCj
                    l8JMZWn80XIhyRXIoX5cFmp3zoFeWYJmEffFBc8aS3+Nnj5sW3HUcapuMP8GE++u
                    pgwfAoGBAJ7xAqIGYcbYnmkayEaoxYB2nxzFQmZSxKF1TBkNyXrTU7ecWb9Ptfjx
                    /gDyDpOsfNd0KW7zwhPv6mBVj+0Lv1J0+QwpIlTDsetLoclq88gtIOqDvCvhSS8H
                    VrNQveGWnUbST+nn0GAOmTI1wnwPIa3DMQjXLR1UWhEv2S39vG38
                    -----END RSA PRIVATE KEY-----

